module.exports = {
  plugins: [
    'cleanupAttrs',
    'removeDoctype',
    'removeXMLProcInst',
    'removeComments',
    'removeMetadata',
    'removeTitle',
    'removeDesc',
    'removeUselessDefs',
    'removeEditorsNSData',
    'removeEmptyAttrs',
    'removeHiddenElems',
    'removeEmptyText',
    'removeEmptyContainers',
    // 'removeViewBox',
    'cleanupEnableBackground',
    'convertStyleToAttrs',
    'convertColors',
    'convertPathData',
    'convertTransform',
    'removeUnknownsAndDefaults',
    'removeNonInheritableGroupAttrs',
    'removeUselessStrokeAndFill',
    'removeUnusedNS',
    'cleanupIDs',
    'cleanupNumericValues',
    'moveElemsAttrsToGroup',
    'moveGroupAttrsToElems',
    'collapseGroups',
    'removeRasterImages',  // xlink:href="data:image
    'mergePaths',
    'convertShapeToPath',
    'sortAttrs',
    'removeDimensions',
    'cleanupListOfValues',
    'removeOffCanvasPaths',
    'reusePaths',
    'mergeStyles',
    { name: 'removeAttrs', params: { attrs: '(stroke|stroke-width|version|x|y|enable-background|space|fill)' } },
    { name: 'addAttributesToSVGElement', params: { attribute: 'fill="#fff"' } }

  ]

}
