name: Generate icons
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generate-icons
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm install --save       
      - run:  npm run SV
      - run:  npm run Test

      - name: tree 
        run: |
         echo ***/icons/***
         tree -h ./icons/
         echo ***/output/***
         tree -h ./output/

      - name: json build
        run: |
         cp ${{ github.workspace }}/dev-badge-icon/icons/*.svg ${{ github.workspace }}/generate-icons/icons
         npm run build
         tree -h ${{ github.workspace }}/generate-icons -I node_modules

      - name: Update
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          mv ${{ github.workspace }}/generate-icons/output/*.svg ${{ github.workspace }}/dev-badge-icon/icons
          mv ${{ github.workspace }}/generate-icons/icons.json ${{ github.workspace }}/dev-badge-icon
          git status
          git add ${{ github.workspace }}/dev-badge-icon/icons/*.svg     
          git add ${{ github.workspace }}/dev-badge-icon/icons.json
          git commit -m "new icon relase"
          git push


        
     

