name: Publish Package to npmjs
on:
  workflow_dispatch:
  workflow_run:
   workflows: ["Generate icons"]
   types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.VERSION }}
      output2: ${{ steps.step1.outputs.SVG }}
    defaults:
      run:
        working-directory: ./dev-badge-icon
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_CONTEXT: ${{ toJson(github) }}    
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: VERSION
        id: step1
        shell: bash      
        run: |
          cd ${{ github.workspace }}/dev-badge-icon
          VERSION=$(npm version patch)   
          echo VERSION=$VERSION
          echo "::set-output name=VERSION::$(echo $VERSION)"   
          SVG=$(find ${{ github.workspace }}/generate-icons/ -name '*.svg' -type f -printf "%f\n")
          echo "::set-output name=SVG::$(echo $SVG)" 
      - run: npm ci
      - run: npm publish
      - run: npm version ${{ github.event.release.tag_name }}
      - run: echo "$GITHUB_CONTEXT"
      - run: npm run version

