name: Publish Package to npmjs
on:
  workflow_dispatch:
  workflow_run:
   workflows: ["Generate icons"]
   types: [completed]
   tags:
    - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./dev-badge-icon
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      

      - run: npm install --save 
      - name: VERSION
        shell: bash      
        run: |
          VERSION=$(npm version patch --dry-run)   
          echo VERSION=$VERSION       
      - run: npm ci
      - run: npm publish --dry-run
      - run: npm version ${{ github.event.release.tag_name }}
      - run: echo "$GITHUB_CONTEXT"
      - run: npm run version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}


